# Generated by Django 2.2.7 on 2020-02-12 11:04

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users', validators=[users.models.User.validate_image]),
        ),
    ]
