# Generated by Django 2.2.7 on 2019-12-26 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(blank=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('storeLink', models.URLField(blank=True, max_length=300)),
                ('trailerUrl', models.URLField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='games')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
