# Generated by Django 2.2.7 on 2020-01-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='comments',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
