# Generated by Django 2.2.7 on 2019-12-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='./default.jpg', upload_to='games/'),
        ),
    ]
