# Generated by Django 2.2.7 on 2020-01-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='comments',
        ),
    ]
