# Generated by Django 2.2.7 on 2020-02-12 11:04

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='games', validators=[games.models.Game.validate_image]),
        ),
    ]
